### ISSUE TITLE
Decide where workshops will be held (IRC network and channel) and announce to mailing list

### ISSUE THREAD

**Issue by michaelfolkson** [ariard/L2-zoology#10]
The first workshop is June 15th which is within 2 weeks. 

[This](https://github.com/ariard/L2-zoology/blob/master/workshops/june-schedule.md) states that:

> Discussions will happen on the new chan #l2-onchain-support freenode.

Is that still the location for the workshops (it is fine it is)? If not this needs to be updated and the mailing list should be updated well in advance of the first workshop. 

I'm on the l2-onchain-support channel on Libera but no one else is and I think the channel registration process doesn't happen overnight. If it is to be Libera maybe it is worth having the workshops on the lightning-dev channel? That would be my personal preference I think.

**Comment by michaelfolkson** [comment]
Yesterday's Lightning spec meeting was on the lightning-dev Libera channel

**Comment by ariard** [comment]
Thanks, the #l2-onchain-support channel has been registered and workshops will happen there as scheduled.

Main motivations to have a dedicated communication space is a) tx-relay/mempool acceptance are wider issues than LN ones b) we might have another serie of workshops in the future

**Comment by michaelfolkson** [comment]
Cool, makes sense. I'd still inform the mailing list that it will be on Libera and not Freenode as originally advertised.
